"""First Revision

Revision ID: 617407a05efd
Revises: 
Create Date: 2020-06-17 02:55:09.180633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "617407a05efd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("network_updated_by_id_fkey", "network", type_="foreignkey")
    op.drop_column("network", "updated_by_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "network",
        sa.Column("updated_by_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "network_updated_by_id_fkey", "network", "user", ["updated_by_id"], ["id"]
    )
    # ### end Alembic commands ###
